### ISSUE TITLE
SKIP_HEADER missing in py3.10

### ISSUE THREAD

**Issue by doc-hex** [coinkite/coinkite-tap-proto#31]
```python
Python 3.10.5 (main, Jun 23 2022, 17:15:32) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib3.util import SKIP_HEADER
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'SKIP_HEADER' from 'urllib3.util' (/usr/local/lib/python3.10/site-packages/urllib3/util/__init__.py)

**Comment by scgbckbone** [comment]
![Screenshot from 2022-09-28 16-56-18](https://user-images.githubusercontent.com/25349625/192812772-2d6d2c7b-266d-495d-b5c1-53e220ce4f34.png)

**Comment by scgbckbone** [comment]
<img width="569" alt="Screenshot 2022-09-28 at 17 45 23" src="https://user-images.githubusercontent.com/25349625/192825526-a5c8f24d-becf-4475-9877-e7005339e4af.png">

**Comment by scgbckbone** [comment]
works for me on both linux/Mac

**Comment by doc-hex** [comment]
- please cut-n-paste text (in `\`\`\` block) instead of these screen shots. 
- more version data:

```
/usr/local/opt/python@3.10/bin/python3.10
Python 3.10.5 (main, Jun 23 2022, 17:15:32) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib3
>>> urllib3.__file__
'/usr/local/lib/python3.10/site-packages/urllib3/__init__.py'
>>> urllib3.__version__
'1.25.11'
>>> from urllib3.util import SKIP_HEADER
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'SKIP_HEADER' from 'urllib3.util' (/usr/local/lib/python3.10/site-packages/urllib3/util/__init__.py)
>>> 
```

**Comment by scgbckbone** [comment]
https://github.com/coinkite/coinkite-tap-proto/pull/32

**Comment by doc-hex** [comment]
Thanks!
