### ISSUE TITLE
`TypeError` on JSON Export

### ISSUE THREAD

**Issue by mvrahden** [coinkite/coinkite-tap-proto#48]
I get a `TypeError` on `cktap json` command:

This is the output:

```sh
$ cktap json
Enter spending code: 
Traceback (most recent call last):
  File "/opt/homebrew/bin/cktap", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/cktap/cli.py", line 813, in json_dump
    rv['account'] = int(path_comps[-1][:-1])
TypeError: 'int' object is not subscriptable
```

```sh
$ cktap version
1.0.3
```

**Comment by scgbckbone** [comment]
great catch, thank you


fix incoming https://github.com/coinkite/coinkite-tap-proto/pull/50
